name: playground
description: My online playground.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0

flutter:
  uses-material-design: true
  fonts:
    - family: Fraunces 72pt
      fonts:
        - asset: assets/fonts/Fraunces72ptSuperSoft-Regular.ttf
        - asset: assets/fonts/Fraunces72ptSuperSoft-Italic.ttf
          style: italic
    - family: Fraunces 9pt
      fonts:
        - asset: assets/fonts/Fraunces9ptSuperSoft-Regular.ttf

import_sorter:
  comments: false